### ISSUE TITLE
[REQUEST] the.zman.trtl

### ISSUE THREAD

**Issue by the-zman** [turtlecoin/.trtl#17]
Webmaster Github: the-zman

Webmaster Discord: thezman

Webmaster Email: zinger@lavacoms.com

Domain: the.zman.trtl

Your server IP address: Where will this domain be pointing? i don’t have a server

Purpose: What will this domain be used for? fun turtle stuff

**Comment by brandonlehmann** [comment]
If you don't have a server, do you have an existing site to point it at?
