### ISSUE TITLE
[REQUEST] wrkz.fork.trtl

### ISSUE THREAD

**Issue by wrkzdev** [turtlecoin/.trtl#18]
Webmaster Github: wrkzdev

Webmaster Discord: CapEtn#4425

Webmaster Email: team@wrkz.work

Domain: wrkz.fork.trtl

Your server IP address: CNAME to fork.wrkz.work

Purpose: Blog for WrkzCoin and other fork stuffs.

**Comment by brandonlehmann** [comment]
This has been added and works as expected:

![image](https://user-images.githubusercontent.com/20562132/56659899-3993cf00-666c-11e9-9071-d3d94f0330d6.png)

However, CloudFlare (where you have it pointed at) doesn't know how to interpret the domain `wrkz.fork.trtl` so you'll either need to fix that up or set up a redirect elsewhere.
