### ISSUE TITLE
[REQUEST] turtle.dev.trtl

### ISSUE THREAD

**Issue by nthon** [turtlecoin/.trtl#27]
Webmaster Github: nthon

Webmaster Discord: Hon

Webmaster Email: admin@cryptomine.cx

Domain: turtle.dev.trtl

Your server IP address: 167.86.81.101

Purpose: run turtlecoin public node

**Comment by brandonlehmann** [comment]
@RocksteadyTC This probably needs a new free subdomain -- `.node.trtl` for requests like this.

**Comment by RocksteadyTC** [comment]
Im okay with that.

**Comment by RocksteadyTC** [comment]
Please resubmit with the new domain
