### ISSUE TITLE
[REQUEST] greywolf.user.trtl

### ISSUE THREAD

**Issue by old-greywolf** [turtlecoin/.trtl#28]
Webmaster Github:  old-greywolf

Webmaster Discord: greywolf

Webmaster Email: TRTLgreywolf@protonmail.com

Domain: greywolf.user.trtl

Your server IP address:  50.62.67.1

Purpose: this domain will be parked until i figure out what to do with it

**Comment by brandonlehmann** [comment]
Updated to greywolf.user.trtl
