### ISSUE TITLE
[REQUEST] rashedmyt.dev.trtl

### ISSUE THREAD

**Issue by rashedmyt** [turtlecoin/.trtl#31]
Webmaster Github: rashedmyt

Webmaster Discord: rashedmyt#8997

Webmaster Email: chandu.rashed@gmail.com

Domain: rashedmyt.dev.trtl

Your server IP address: https://rashedmyt.github.io

Purpose: Probably my portfolio website

**Comment by RocksteadyTC** [comment]
approved, make a PR here with your record https://github.com/turtlecoin/.trtl/blob/master/config/dev.trtl.zone

Please keep in mind whether you'll need an A record, CNAME, or TXT record

**Comment by rashedmyt** [comment]
done #32

**Comment by RocksteadyTC** [comment]
solved in https://github.com/turtlecoin/.trtl/commit/1045368aa8b23fa4fba96aefc2729d1ad80f8d57
