### ISSUE TITLE
[REQUEST] turtlepay.trtl

### ISSUE THREAD

**Issue by brandonlehmann** [turtlecoin/.trtl#4]
Webmaster Github: @brandonlehmann 

Webmaster Discord: @iburnmycd#0001 

Webmaster Email: turtlepay@protonmail.com

Domain: turtlepay.trtl, pay.trtl

Your server IP address: N/A. Requesting NS record instead of A record for delegation. 

Purpose: What will this domain be used for? TurtlePay

**Comment by thinkpol2** [comment]
pay.trtl would be nice for short-form URLs here, e.g. pay.trtl/V-_O7nl0Ii0

**Comment by brandonlehmann** [comment]
This too
