### ISSUE TITLE
[REQUEST] mapping4.trtl

### ISSUE THREAD

**Issue by afterconnery** [turtlecoin/.trtl#41]
Webmaster Github: afterconnery

Webmaster Discord: afterconnery #5552

Webmaster Email: seandreas@protonmail.com

Domain: mapping4.trtl

Your server IP address: afterconnery.github.io

Purpose: Offering a donation site for mapping specific areas on openstreetmap.

**Comment by brandonlehmann** [comment]
Request is approved. Please send a transaction on the network of 0 TRTL with a 15,000 TRTL fee and provide the transaction hash of the transaction. Then feel free to submit the PR to the main zone https://github.com/turtlecoin/.trtl/blob/master/config/domain-config with the following entry. Please include the transaction hash in your PR request for validation.

`mapping4                    IN        CNAME   afterconnery.github.io.`
