### ISSUE TITLE
This add-on not working on Firefox 76.0

### ISSUE THREAD

**Issue by Nokia808** [turtlecoin/.trtl#45]
Hi. I tested this add-on on my Firefox 76.0 & it is not working ! I tried to visit http://nx.bit but it does not worked at all. I entered whole "http://nx.bit" & tried to refresh for multiple times but not worked.

**Comment by Nokia808** [comment]
I did not label this as "REQUEST" ! I only edit title but this label added !

**Comment by brandonlehmann** [comment]
This issue belongs on https://github.com/turtlecoin/.trtl-extension-firefox

**Comment by brandonlehmann** [comment]
Also, to add, `.bit` support was dropped from OpenNIC last year. As such, the nameservers that the extension uses does not support the TLD `.bit`

**Comment by Nokia808** [comment]
@brandonlehmann 
Thank you for explanation!
But regarding https://github.com/turtlecoin/.trtl-extension-firefox that you refered me,  it has no "issue" section so how we can report an issue about extension ?! Kindly, can you activate "issue" section on repository of extension ?

Also, about this repository: is https://github.com/turtlecoin/.trtl/ of the .trtl DNS itself ?

**Comment by brandonlehmann** [comment]
@Nokia808 no, not for you to open an issue that doesn’t exist. This repo has nothing to do with resolving .bit domains so I’m not sure what you’re asking for.
