### ISSUE TITLE
[REQUEST] YourDomainHere.trtl

### ISSUE THREAD

**Issue by muneeb111** [turtlecoin/.trtl#52]
Webmaster Github: Your github username here
muneeb111
Webmaster Discord: Your discord username here
muneeb111
Webmaster Email: Your contact email
muhammedaljaari@gmail.com
Domain: Your requested .trtl URL

Your server IP address: Where will this domain be pointing?

Purpose: What will this domain be used for?

**Comment by brandonlehmann** [comment]
Incomplete request :( please try again.
