### ISSUE TITLE
[REQUEST] Prodigal.trtl and Sherlock.trtl

### ISSUE THREAD

**Issue by Bytase** [turtlecoin/.trtl#55]
Webmaster Github: bytase

Webmaster Discord: bytasetrader

Webmaster Email: bytase@gmail.com

Domain: prodigal.trtl and Sherlock.trtl

Your server IP address: 50.116.22.194

Purpose: Serves as a website for my pet Turtle, named Sherlock. Future plans pending.

**Comment by RocksteadyTC** [comment]
cool send 15,000 TRTL to @iburnmycd on discord and we can get you merged in

**Comment by RocksteadyTC** [comment]
stale issue, closing
