### ISSUE TITLE
[REQUEST] rejected.trtl

### ISSUE THREAD

**Issue by himdid** [turtlecoin/.trtl#56]
Webmaster Github: Your github username here
himdid

Webmaster Discord: Your discord username here
MemesDidIt#5430

Webmaster Email: Your contact email
himdid@protonmail.com

Domain: Your requested .trtl URL
rejected.trtl

Your server IP address: Where will this domain be pointing?
https://rejected.life (for now. I plan on setting up a node soon. esp when we switch to pos and it will direct to that instead)

Purpose: What will this domain be used for?
redirecting a node

**Comment by RocksteadyTC** [comment]
cool send 15,000 TRTL to @iburnmycd on discord and we can get you merged in
