### ISSUE TITLE
teglicho.node.trtl

### ISSUE THREAD

**Issue by teglicho** [turtlecoin/.trtl#57]
Webmaster Github: teglicho

Webmaster Discord: teglicho

Webmaster Email: teglicho@gmail.com

Domain: teglicho.node.trtl

Your server IP address: 78.142.26.26

Purpose: Node server

**Comment by brandonlehmann** [comment]
Handled in https://github.com/turtlecoin/.trtl/commit/5f4f474e6bae6d9e1e6c12b6bad33d4716f74c5c
