### ISSUE TITLE
[REQUEST] extra.trtl

### ISSUE THREAD

**Issue by ExtraHash** [turtlecoin/.trtl#6]
Webmaster Github: ExtraHash

Webmaster Discord: ExtraHash

Webmaster Email: extrahash@protonmail.com

Domain: extra.trtl

Your server IP address: 142.93.21.48

Purpose: personal website / home for my turtle projects

**Comment by fexra** [comment]
Should be extra.user.trtl

**Comment by Sajo8** [comment]
He could pay for it @fexra

**Comment by fexra** [comment]
> He could pay for it @fexra

refer to #7

**Comment by ExtraHash** [comment]
I was given this pay domain for free in exchange for my assistance in testing, and since this is the first-ever turtle domain aside from official ones, I believe it should remain for historical purposes @fexra

**Comment by fexra** [comment]
> I was given this pay domain for free in exchange for my assistance in testing, and since this is the first-ever turtle domain aside from official ones, I believe it should remain for historical purposes @fexra

Have a pitchfork lad, I know when @brandonlehmann lives.

**Comment by brandonlehmann** [comment]
I believe we call this grandfathered in.
