### ISSUE TITLE
[REQUEST] YourDomainHere.trtl

### ISSUE THREAD

**Issue by tr1pp** [turtlecoin/.trtl#60]
Webmaster Github: tr1pp

Webmaster Discord: tr1ppy

Webmaster Email: aonghaswill@hotmail.com

Domain: public.node.trtl

Your server IP address: 209.145.49.61

Purpose: Will host a public node

**Comment by RocksteadyTC** [comment]
@brandonlehmann im cool with it if you're cool with it

**Comment by brandonlehmann** [comment]
> @brandonlehmann im cool with it if you're cool with it

fine with me -- not sure how much traffic that'll hit it though

**Comment by RocksteadyTC** [comment]
Approving, please create a PR with your record added alphabetically 
Thanks!
