### ISSUE TITLE
[REQUEST] turtleturtle.trtl

### ISSUE THREAD

**Issue by turtleturtleclub** [turtlecoin/.trtl#61]
Webmaster Github: turtleturtleclub

Webmaster Discord: TurtleTurtle.Club

Webmaster Email: support@turtleturtle.club

Domain: turtleturtle.trtl

Your server IP address: 137.135.105.102

Purpose: Mining pool, nodes and more. 🐢 🐢

**Comment by RocksteadyTC** [comment]
Approving. Please submit the PR with your changes
