### ISSUE TITLE
[REQUEST] fexra.user.trtl

### ISSUE THREAD

**Issue by fexra** [turtlecoin/.trtl#7]
Webmaster Github: fexra

Webmaster Discord: fexra

Webmaster Email: fexra@pm.me

Domain: fexra.user.trtl

Your server IP address: 139.162.155.73

Purpose: personal home page and epic lulz

**Comment by brandonlehmann** [comment]
Should this b e `fexra.user.trtl` ?

**Comment by RocksteadyTC** [comment]
yes

the .user.trtl community hadn't been built yet at the time

**Comment by brandonlehmann** [comment]
> yes
> 
> the .user.trtl community hadn't been built yet at the time

fixed
